import { isRendererCompatible } from "@fdraft/theme-sdk";
import type { FilePlatform } from "../platform/types.js";

export interface FDraftRuntimeCompatibility {
  installedSdkVersion: string;
  installedRendererVersion: string;
  supportedComponentKeys: string[];
  supportedCapabilities: string[];
}

export interface ReadCompatibilityResult {
  status: "ok" | "missing" | "unparseable";
  compatibility?: FDraftRuntimeCompatibility;
  detail: string;
}

const VERSIONS_SEGMENTS = ["src", "infrastructure", "theme-runtime", "installed-versions.generated.ts"];
const COMPATIBILITY_SEGMENTS = ["src", "infrastructure", "theme-runtime", "compatibility.ts"];

function extractStringConst(source: string, name: string): string | undefined {
  return source.match(new RegExp(`${name}\\s*=\\s*"([^"]+)"`))?.[1];
}

function extractStringArrayConst(source: string, name: string): string[] | undefined {
  const match = source.match(new RegExp(`${name}[^=]*=\\s*\\[([\\s\\S]*?)\\]`));
  if (!match) return undefined;
  return [...match[1]!.matchAll(/"([^"]+)"/g)].map((m) => m[1]!);
}

/**
 * FDraft's Prompt 10 integration produces no separate JSON manifest — its
 * real, committed source of truth is two plain TypeScript files:
 * `installed-versions.generated.ts` (never hand-edited, regenerated by
 * FDraft's own `sync-theme-runtime-versions` script) and
 * `compatibility.ts` (`FDRAFT_SUPPORTED_COMPONENT_KEYS`/
 * `FDRAFT_SUPPORTED_CAPABILITIES`). Reading them directly — by regex, not
 * a full TS parser — is a real, honest reading of FDraft's actual
 * committed contract rather than inventing a manifest format it doesn't
 * produce. Fragile only if FDraft restructures these two specific files;
 * `status: "unparseable"` is the honest signal for that, distinct from
 * `"missing"` (this checkout predates Prompt 10 entirely).
 */
export async function readFDraftCompatibility(platform: FilePlatform, repoPath: string): Promise<ReadCompatibilityResult> {
  const versionsPath = platform.join(repoPath, ...VERSIONS_SEGMENTS);
  const compatPath = platform.join(repoPath, ...COMPATIBILITY_SEGMENTS);

  if (!(await platform.exists(versionsPath)) || !(await platform.exists(compatPath))) {
    return {
      status: "missing",
      detail: `Could not find FDraft's theme-runtime integration at ${platform.join(...VERSIONS_SEGMENTS)} and ${platform.join(...COMPATIBILITY_SEGMENTS)} — this checkout may not have Prompt 10's integration yet, or may be on the wrong branch.`,
    };
  }

  const [versionsSource, compatSource] = await Promise.all([platform.readTextFile(versionsPath), platform.readTextFile(compatPath)]);

  const installedSdkVersion = extractStringConst(versionsSource, "INSTALLED_THEME_SDK_VERSION");
  const installedRendererVersion = extractStringConst(versionsSource, "INSTALLED_THEME_RENDERER_VERSION");
  const supportedComponentKeys = extractStringArrayConst(compatSource, "FDRAFT_SUPPORTED_COMPONENT_KEYS");
  const supportedCapabilities = extractStringArrayConst(compatSource, "FDRAFT_SUPPORTED_CAPABILITIES");

  if (!installedSdkVersion || !installedRendererVersion || !supportedComponentKeys || !supportedCapabilities) {
    return { status: "unparseable", detail: "Found FDraft's theme-runtime integration files, but couldn't read the expected version/capability constants out of them — they may have been restructured since this check was written." };
  }

  return { status: "ok", compatibility: { installedSdkVersion, installedRendererVersion, supportedComponentKeys, supportedCapabilities }, detail: "Read FDraft's committed theme-runtime compatibility contract." };
}

export interface PublishCompatibilityCheck {
  compatible: boolean;
  reasons: string[];
}

/** Mirrors FDraft's own `checkThemeCompatibility` logic exactly (same three checks, same source-of-truth arrays) so Studio can give this feedback *before* publish, not just have FDraft silently refuse to render it after. */
export function checkProjectAgainstFDraft(project: { minRendererVersion: string; requiredComponentKeys: string[]; capabilities: string[] }, fdraft: FDraftRuntimeCompatibility): PublishCompatibilityCheck {
  const reasons: string[] = [];
  if (!isRendererCompatible(project.minRendererVersion, fdraft.installedRendererVersion)) {
    reasons.push(`Requires renderer >= ${project.minRendererVersion}, but the linked FDraft has ${fdraft.installedRendererVersion} installed.`);
  }
  const unsupportedComponents = project.requiredComponentKeys.filter((k) => !fdraft.supportedComponentKeys.includes(k));
  if (unsupportedComponents.length > 0) reasons.push(`Uses component(s) FDraft doesn't support yet: ${unsupportedComponents.join(", ")}.`);
  const unsupportedCapabilities = project.capabilities.filter((c) => !fdraft.supportedCapabilities.includes(c));
  if (unsupportedCapabilities.length > 0) reasons.push(`Uses capability/capabilities FDraft doesn't support yet: ${unsupportedCapabilities.join(", ")}.`);
  return { compatible: reasons.length === 0, reasons };
}
