import type { SimulationScenario } from "@fdraft/theme-sdk";

/**
 * Always-available, curated QA scenarios — never saved to the project (no
 * `id`/`name`/`description` collides with a user's own saved scenario
 * because these ids are fixed constants, never regenerated). Mirrors the
 * `STARTER_TEMPLATES` pattern in `../templates/starterTemplates.ts`: a
 * closed, hand-picked list a picker UI offers alongside whatever the
 * project itself has saved under `StudioProjectDocument.simulationScenarios`.
 */
export const DEFAULT_SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: "b333933d-2780-49d6-812b-7c0c12ecf3c8",
    name: "Not opted in",
    description: "A visitor who hasn't opted into the event yet.",
    eventStatus: "active",
    eventActive: true,
    eventAvailable: true,
    optedIn: false,
    draftGenerated: false,
    eventCompleted: false,
    progressPercent: 0,
    watchedCount: 0,
    targetCount: 10,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "normal",
  },
  {
    id: "28d47d96-0744-4b91-b7fe-3cee4dbaa94b",
    name: "Active, halfway through",
    description: "Opted in, draft generated, watching — a typical mid-event visitor.",
    eventStatus: "active",
    eventActive: true,
    eventAvailable: true,
    optedIn: true,
    draftGenerated: true,
    eventCompleted: false,
    progressPercent: 50,
    watchedCount: 5,
    targetCount: 10,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "normal",
  },
  {
    id: "25b87836-f955-4518-9814-842c3e25aeef",
    name: "Event ended",
    description: "The event's phase has ended; nothing is active or available any more.",
    eventStatus: "ended",
    eventActive: false,
    eventAvailable: false,
    optedIn: true,
    draftGenerated: true,
    eventCompleted: true,
    progressPercent: 100,
    watchedCount: 10,
    targetCount: 10,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "normal",
  },
  {
    id: "8a521249-1e2c-4680-a161-1d2757de6fb8",
    name: "Empty / no data yet",
    description: "Representative empty state — no films, no progress, nothing generated.",
    eventStatus: "available",
    eventActive: true,
    eventAvailable: true,
    optedIn: true,
    draftGenerated: false,
    eventCompleted: false,
    progressPercent: 0,
    watchedCount: 0,
    targetCount: 0,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "empty",
  },
  {
    id: "f6711da8-ed06-41e9-9765-c9748061552e",
    name: "Loading",
    description: "Representative loading state for components that fetch their own data.",
    eventStatus: "active",
    eventActive: true,
    eventAvailable: true,
    optedIn: true,
    draftGenerated: false,
    eventCompleted: false,
    progressPercent: 0,
    watchedCount: 0,
    targetCount: 10,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "loading",
  },
  {
    id: "a0b28cde-39bb-4990-8210-54a88cbac5bd",
    name: "Error / failed data",
    description: "Representative error state for components that fetch their own data.",
    eventStatus: "active",
    eventActive: true,
    eventAvailable: true,
    optedIn: true,
    draftGenerated: true,
    eventCompleted: false,
    progressPercent: 30,
    watchedCount: 3,
    targetCount: 10,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "error",
  },
  {
    id: "3044b48f-017d-4e66-a2d7-5eb241d3bb96",
    name: "Long titles",
    description: "Representative unusually-long author-entered titles, to catch clipping/wrapping.",
    eventStatus: "active",
    eventActive: true,
    eventAvailable: true,
    optedIn: true,
    draftGenerated: true,
    eventCompleted: false,
    progressPercent: 40,
    watchedCount: 4,
    targetCount: 10,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "longTitle",
  },
  {
    id: "8e30602b-b111-4c97-ac5d-8850d73ac259",
    name: "Maximum film grid",
    description: "The maximum number of film cards a grid may ever need to lay out.",
    eventStatus: "active",
    eventActive: true,
    eventAvailable: true,
    optedIn: true,
    draftGenerated: true,
    eventCompleted: false,
    progressPercent: 100,
    watchedCount: 40,
    targetCount: 40,
    performanceTier: "high",
    reducedMotion: false,
    dataProfile: "maxFilmCards",
  },
];
